version: '3'

services:
  app:
    image: fulvaz/my-gateway:production
    environment:
      NODE_ENV: ${VAR_ENV}
    ports:
      - 80:80
    volumes:
      - ./log:/var/logs/gateway
    restart: always