version: '3'

services:
  db:
    image: mysql:5.7
    # expose:
    #   - 3306
    ports:
      - 3306
    volumes:
      - /var/mysql/data/db:/var/lib/mysql
      - /var/mysql:/docker-entrypoint-initdb.d/:ro
      - /var/mysql/config/mysql.conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_HOST: "localhost"
      MYSQL_ROOT_PASSWORD:  ${VAR_DB_PASSWORD}
      MYSQL_LOG_CONSOLE: "True"
    restart: always
  
  app:
    image: fulvaz/blog-backend:production
    environment:
      NODE_ENV: ${VAR_ENV}
      DB_PASSWORD: ${VAR_DB_PASSWORD}
      DB_USERNAME: ${VAR_DB_USERNAME}
      DB_HOST: ${VAR_DB_HOST}
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - /var/logs/blog:/var/logs/blog
    restart: always
